name:                aos-dice
version:             0.1.0.0
github:              "michaelsproul/aos-dice"
license:             BSD-3-Clause
author:              "Michael Sproul"
maintainer:          "firstname@lastname.xyz"
copyright:           "2024 Michael Sproul"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michaelsproul/aos-dice#readme>

dependencies:
- base >= 4.7 && < 5
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  aos-dice-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aos-dice
